### PR TITLE
Manifest V3 update.

### PR DESCRIPTION
**Pull request by kellenmurphy**
I took a stab at Issue #79. For the most part this was a straightforward, following the Chrome [Migration Path](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration). 

## Changes

- browserAction has been replaced by a [more generic action](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#action-api-unification).
- there are some permissions changes, namely that '<all_urls>' is now a [host permission](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#host-permissions) and that we don't need webRequestBlocking (see note below re: the [reviseRedirectedRequestMethod](https://github.com/simplesamlphp/SAML-tracer/blob/main/src/SAMLTrace.js#L707) issue) raised in #79 by @khlr.
- we now refer the background script as a "service worker" instead of a background script

## Notes

- We **do not want to merge this now** to main, as Manifest V3 is unsupported by Firefox at the moment, though will be out [later this year](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/). I think it may make sense to keep this around in a feature branch until then, however, so I'm contributing the code I have now. 
  - I checked and even my Firefox Dev Edition (104.0b3), which has an `about:config` option (`extensions.manifestV3.enabled`) to "support" MV3, doesn't yet support service workers... so we're kind of dead in the water with MV3 development at the moment.

 - Re: the necessity of blocking permissions for [reviseRedirectedRequestMethod](https://github.com/simplesamlphp/SAML-tracer/blob/main/src/SAMLTrace.js#L707)

   - I took a look at where the requirement for this code came from in the [original issue](https://github.com/SimpleSAMLphp/SAML-tracer/pull/23#issuecomment-345540591) cited within the code, and referencing [this StackOverflow post](https://stackoverflow.com/questions/47379439/webrequest-api-redirect-uses-http-method-of-parent-request) and I have to be completely honest here, try as a I might I was unable to replicate. Obviously, I'm not leveraging the versions of Chrome and FF from back then, but despite throwing many test cases of POSTs followed by GETs I did not see untracked requests within SAML-Tracer.

   - That said, that *does not prove* that we don't have an issue. *The absence of evidence is not the evidence of absence.* In particular, either (a) webRequest has changed since that time, or (b) I'm not replicating the issue correctly.

   - Re: (a), I'm not in a position to comment since I've not done this research. :wink:

   - Re: (b), I'm not in a position to comment since *I'm* the cause of that issue.

   - For what it's worth, I think there's a *strong* likelihood that I'm not replicating the previous issue correctly... but I will expound on what I did:

     - I tested with the https://wiki.surfnet.nl/ SP, as described in the original issue: https://github.com/SimpleSAMLphp/SAML-tracer/pull/23#issuecomment-344970423

     - I tested with my own Shibboleth and SimpleSAMLphp dev environment and forcing POSTs followed by GETs.

     - I tested with two Shibboleth IDPs that are configured as proxied instances to upstream IDPs... one a "production" quality system I maintain that upstreams to Okta, and another my development proxy instance running in Azure that's got a selectable selection of upstreams (Shibboleth, WSO2 IS, Azure, and Keycloak).

     - At no point with ANY of these was I able to "break" things insofar as non-tracked SAML assertions being logged.

  - So while I do not want to say with 100% certainty that "it's working", I would be relatively comfortable stating that I have some degree of confidence that it's working, and that I think the next step is for some others to test to confirm my findings / validate that they can't replicate.
 
 - And lastly, by "replicate" I should also clarify to mean that I cannot get [these lines of code](https://github.com/simplesamlphp/SAML-tracer/blob/55dd45c5b9527f3308482b6bc48ebf3294f5e73b/src/SAMLTrace.js#L722-L725) to activate under any of the test circumstances described above.

### CODE REVIEW

**Comment by khlr** [comment]
Thank you so much for this PR, @kellenmurphy! I really like your detailed explanations!

Regarding the reviseRedirectedRequestMethod-issue:

IIRC case 1 affected Chrome _and_ Firefox. At least at that time. Since case 2 is/was a FF-only special treatment we can ignore it for the moment.
So I focused on case 1. And yep, I can't reproduce it either! But have a try using Firefox (without your MV3-changes). Then you _can_ activate the mentioned lines! Maybe have a try, too. Go [here](https://wiki.surfnet.nl/login.action?os_destination=%2F) and then select _Academisch Medisch Centrum (AMC)_.
If you set a breakpoint within the if, you'll reach that line! But only in FF and not in Chrome...

Possibly Chrome changed "something" in the meantime... So maybe both cases are FF-only speacial treatments by now ¯\\\_(ツ)\_/¯

Hence I think at the moment we can't clarify if altering the method will break something in the future...

**Review by khlr — CHANGES_REQUESTED** [review]
Please adjust the [keyboard-shortcut](https://github.com/simplesamlphp/SAML-tracer/blob/d1e4ed6dea379694c58145fd6ab8aa45e3ea2c17/manifest.json#L34):
`"_execute_browser_action"` to `"_execute_action"`

**Comment by kellenmurphy** [comment]
@khlr great insights! I will check [this](https://github.com/simplesamlphp/SAML-tracer/pull/80#issuecomment-1200244506) out later this week to see if I can replicate, and I will also update the keyboard-shortcut code.

Thanks!!! I'll have more soon... (my week is very front-heavy).

**Comment by kellenmurphy** [comment]
Just an update... I'm still planning to work on this, I've just had to be away for a bit due to a death in the family. I'll be circling back to this soon!

**Comment by tvdijen** [comment]
My sincerest condolences @kellenmurphy ! First things first!

**Comment by kellenmurphy** [comment]
Thanks @tvdijen... 

FWIW I just fixed the keyboard shortcut, but I do still need to do some digging in line with @khlr [comment](https://github.com/simplesamlphp/SAML-tracer/pull/80#issuecomment-1200244506) above. We also obviously need to wait for Firefox to start supporting MV3.

**Comment by khlr** [comment]
Hello @kellenmurphy 👋

How are you? Do you think you'll find the time picking up this issue again?

**Comment by kellenmurphy** [comment]
Sure! I can probably get to that next week. 😀

Kellen Murphy
***@***.***

________________________________

**Comment by kellenmurphy** [comment]
@khlr I'm picking this back up this week. I've rebased onto simplesamlphp/main to pick up the recently approved PC, and squashed the previous commits to clean up the PR (and amended the commit message text). 

I'm planning to carve out some time this week to thoroughly test this... it's been over a year (!) since I last looked at this so I want to vet this thoroughly.

**Comment by kellenmurphy** [comment]
@khlr I inadvertently requested review. Disregard. Mis-click. See my last message this isn't ready to review yet.

**Comment by tvdijen** [comment]
It's back to where you were after my earlier rebase-mistake.
I've kept a backup in the `[manifest-backup](https://github.com/simplesamlphp/SAML-tracer/tree/manifest-backup)` branch, just in case

**Comment by rileyw** [comment]
Any thoughts on next steps for this PR recognizing that this extension will stop working in Chrome with manifest-v2 extensions will stop working "soon."

**Comment by thijskh** [comment]
I've given it a test on Chrome and my scenarios seem to work just fine, including several different SAML flows, a WSFED flow and import/export.

When trying to load the zip built from this PR into Firefox 129 I get an error that the extension is damaged (without meaningful information to me what is exactly wrong).

It might be nice to rebase this PR since there's a (simple) merge conflict now in manifest.json.

**Comment by tvdijen** [comment]
I've taken care of the rebase.. I've also figured out what is wrong with the extension to be able to use it in Firefox. Mozilla provides a `web-ext` npm-package that can be used to verify your extension and sign it. The tools reports the following issues:

afbeelding

**Comment by tvdijen** [comment]
Ok, second update:  I can install the addon in Firefox developer edition. Apparently Firefox doesn't allow disabling signature-checking on regular versions.. Everything works fine, so I think we can just merge this and get it released

**Comment by tvdijen** [comment]
@khlr With your permissions I'm merging this and tagging a new 1.8 release. I understand you have the ability to upload this release to the app stores?
I think we should just try it and see what next bump in the road we hit, but I'm fairly confident with it now.

**Comment by khlr** [comment]
I could check out the code tomorrow and test it a bit. Is there any interest? Wouldn't hurt imho. 🤓

**Comment by tvdijen** [comment]
Sure, take your time and test. Just make sure to use Firefox Developer edition.. Chrome is fine with loading unsigned unpacked add-ons.

**Comment by khlr** [comment]
I can't download the Firefox Developer Edition right now. That's why I only looked at it with Chrome by now.

Chrome lists 2 warnings (no errors, “just” warnings"):

1.  'background.scripts' requires manifest version of 2 or lower.
2. Unrecognized manifest key 'browser_specific_settings'.

Warning 2 can probably be ignored as Chrome just seems to be unaware of this option. It's not particularly “nice” that it becomes a warning. But we can certainly live with it if you can't somehow teach Chrome not to complain here?

Regarding warning 1: Can't we just drop the line `"scripts": ["bootstrap.js"]` since it's not required for mv3 extensions anyway?

**Comment by tvdijen** [comment]
Yes it is required.. Firefox never implemented service workers in their implementation of manifest v3.
That's the entire point I made in my comments yesterday..

**Comment by khlr** [comment]
Oh boy... Sorry, I didn't reall take note of that 🫣

**Comment by khlr** [comment]
I just tested it using FF. Looks good, everything seems to run as expected :)

As expected, however, FF ‘warns’ of the unknown `background.service_worker`... 😉
At some point, FF will surely catch up with Chrome, and hopefully we will no longer have to use the different properties.

From my point of view, there is now nothing to be said against merging this PR 👍

**Pull request merged**
