### PR TITLE
Update resource mime-types

### PR DESCRIPTION
**Pull request by tvdijen**
See https://stackoverflow.com/a/5142316/5494155

### CODE REVIEW

**Review by khlr — APPROVED** [review]

**Comment by thijskh** [comment]
Not so sure about removing legacy types since the webserver decides this and we want to have SAML tracer work on e.g. services running RHEL-like OS'es.

**Comment by thijskh** [comment]
This is superseded by #92, if accepted.

**Comment by tvdijen** [comment]
> Not so sure about removing legacy types since the webserver decides this and we want to have SAML tracer work on e.g. services running RHEL-like OS'es.

I figured that Feb 2017 (the introduction of the `font/` RFC) was long enough in the past..
I've tested on an Apache 2.2 server on RHEL 7 and that one doesn't send a `content-type` header at all for woff2-files.

**Comment by thijskh** [comment]
My CentOS 7 install lists `application/font-woff` in `/etc/mime.types` for extension `woff`, but indeed nothing for `woff2` so that will by default go without a type.

**Comment by tvdijen** [comment]
I'm OK with keeping them, but let's add a note to this comment for future reference.

**Comment by thijskh** [comment]
Did that.

**Pull request closed without merging**
